import Foundation

public enum SwiftClientGenerator {
    public static func generate(_ contract: ContractSchema) throws -> String {
        try contract.validate()
        let api = contract.name + "API"
        func type(_ value: String) -> String {
            if value.hasSuffix("?") { return type(String(value.dropLast())) + "?" }
            if value.hasPrefix("[") { return "[" + type(String(value.dropFirst().dropLast())) + "]" }
            return "`\(value)`"
        }
        var lines = ["// Generated by TalkClientGenerator. Edit Contract.talk.json; do not edit this file.",
                     "import Foundation", "import Talk", ""]
        for dto in contract.types {
            if dto.kind == "enum" {
                lines.append("public enum `\(dto.name)`: String, Codable, Sendable, Equatable, CaseIterable {")
                for item in dto.cases ?? [] { lines.append("    case `\(item)`") }
            } else {
                let fields = dto.fields ?? []
                lines.append("public struct `\(dto.name)`: Codable, Sendable, Equatable {")
                for field in fields { lines.append("    public let `\(field.name)`: \(type(field.type))") }
                lines.append("    public init(\(fields.map { "`\($0.name)`: \(type($0.type))" }.joined(separator: ", "))) {")
                for field in fields { lines.append("        self.`\(field.name)` = `\(field.name)`") }
                lines.append("    }")
            }
            lines.append("}\n")
        }
        lines.append("public enum \(api) {")
        lines.append("    public static let contractID = \"\(contract.contractID)\"")
        lines.append("    public static let contractVersion = \"\(contract.contractVersion)\"")
        let schemaData = try JSONEncoder().encode(contract)
        let schemaLiteral = String(decoding: try JSONEncoder().encode(String(decoding: schemaData, as: UTF8.self)), as: UTF8.self)
        lines.append("    public static let schema: ContractSchema = try! ContractSchema.load(Data(\(schemaLiteral).utf8))")
        lines.append("    public static let requirement = ContractRequirement(schema: schema)")
        for action in contract.actions { lines.append("    public static let `\(action.symbol)` = \"\(action.id)\"") }
        for event in contract.events { lines.append("    public static let `\(event.symbol)` = \"\(event.id)\"") }
        lines.append("    public static let scopes: Set<String> = [\(Set(contract.actions.map(\.scope)).sorted().map { "\"\($0)\"" }.joined(separator: ", "))]")
        lines.append("    public static let actions: [String: String] = [\(contract.actions.map { "`\($0.symbol)`: \"\($0.scope)\"" }.joined(separator: ", "))]")
        lines.append("}\n")
        lines.append("public struct \(contract.name)Client: Sendable {")
        lines.append("    public let transport: TalkClient")
        lines.append("    public let requirement: ContractRequirement")
        lines.append("    public init(transport: TalkClient, requiredActions: Set<String>? = nil, requiredEvents: Set<String>? = nil, minimumMinor: Int = 0) {")
        lines.append("        self.transport = transport")
        lines.append("        self.requirement = ContractRequirement(schema: \(api).schema, actions: requiredActions, events: requiredEvents, minimumMinor: minimumMinor)")
        lines.append("    }")
        lines.append("    public func connect() async throws { try await transport.connect(requirement: requirement) }")
        for action in contract.actions {
            lines.append("    /// \(action.mutation ? "Mutation" : "Read/subscription"). Never automatically retried after uncertain delivery.")
            let parameter = action.input == "Void" ? "" : "_ input: \(type(action.input)), "
            let payload = action.input == "Void" ? ".null" : ".encoding(input)"
            let output = action.output == "Void" ? "Void" : type(action.output)
            lines.append("    public func `\(action.method)`(\(parameter)timeout: Double = 10) async throws -> \(output) {")
            if action.output == "Void" {
                lines.append("        let result = try await transport.request(action: \(api).`\(action.symbol)`, payload: \(payload), timeout: timeout, requirement: requirement)")
                lines.append("        guard result == .null else { throw TalkError.invalidMessage }")
            } else {
                lines.append("        return try await transport.request(action: \(api).`\(action.symbol)`, payload: \(payload), timeout: timeout, requirement: requirement).decode(\(type(action.output)).self)")
            }
            lines.append("    }")
        }
        if !contract.events.isEmpty {
            lines.append("    public enum Event: Sendable, Equatable {")
            for event in contract.events { lines.append("        case `\(event.symbol)`(\(type(event.payload)))") }
            lines.append("    }")
            lines.append("    public func decodeEvent(_ message: TalkMessage) throws -> Event {")
            lines.append("        try message.validate()")
            lines.append("        guard message.kind == .event else { throw TalkError.invalidMessage }")
            lines.append("        switch message.action {")
            for event in contract.events {
                lines.append("        case \(api).`\(event.symbol)`: return .`\(event.symbol)`(try message.payload.decode(\(type(event.payload)).self))")
            }
            lines.append("        default: throw TalkError.unknownAction")
            lines.append("        }")
            lines.append("    }")
        }
        lines.append("}\n")
        return lines.joined(separator: "\n")
    }
}
